parameters:
#    civi_hello.example.class: Civi\HelloBundle\Example

services:
#    civi_hello.example:
#        class: %civi_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
